name: elasticsearch-kibana
version: '1.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    cpus: 0.5
    mem_limit: 1G
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    container_name: kibana
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    cpus: 0.5
    mem_limit: 512M
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  esdata:
