filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

filebeat.config.modules:
  enabled: true
  path: /usr/share/filebeat/modules.d/*.yml

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]
